language: node_js

node_js:
  - "11"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn build
  - docker build -t utohub.com:latest . --no-cache

deploy:
  - provider: script
    script: deploy_production.sh
    on:
      branch: master


after_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  - docker push $REGISTRY/utohub/utohub.com:latest
  - docker rmi -f utohub.com:latest
  - docker logout
