language: node_js

node_js:
  - "11"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn build
  - docker build -t utohub.com:latest . --no-cache

after_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  - docker tag utohub.com:latest $REGISTRY/utohub/utohub.com:latest
  - docker push $REGISTRY/utohub/utohub.com:latest
