language: node_js

node_js:
  - "11"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - ./build_image.sh

after_script:
  - ./push_assets.sh
  - ./push_image.sh